import mongoose, { Mongoose, Schema } from "mongoose";

const userSchema = new mongoose.Schema(
  {
    //id: automatic generated by mongoose as _id
    name: {
      type: String,
      required: true,
    },
    phoneNumber: {
      type: String,
      required: true,
      unique: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
    },
    password: {
      type: String,
      required: true,
    },
  },
  {
    timestamps: true, // cria automaticamente createdAt e updatedAt
  }
);

export default mongoose.model("User", userSchema);